openapi: 3.0.0
info:
  title: Platform-API
  version: 1.0.0
paths:
  '/kafka/{topic}':
    parameters:
      - name: topic
        description: the name of the target topic in kafka 
        in: path
        required: true
        schema: 
          type: string
    post:
      security:
      - bearerAuth: []
      summary: proxies json messages to kafka rest proxy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                records:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: 'the successful response from kafka rest proxy'
          content:
            application/json:
              schema:
                type: object
        '401':
          description: invalid/missing jwt token
          content:
            application/json:
              schema:
                example: '{"message": "invalid jwt"}'
                type: string
        '500':
          description: Internal server error
  '/clinical/program/{programId}/all-clinical-data':
    parameters:
      - name: programId
        description: the short name of the program
        in: path
        required: true
        schema:
          type: string
    get:
      security:
      - bearerAuth: []
      summary: Download a zip file with tsv files for all clinical data in program
      description: '- the file name of the zip file is not determined by this endpoint'
      responses:
        '200':
          description: 'A zip file with all program submitted data'
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error
  '/clinical/template/all':
    get:
      summary: Download a zip file with templates for all schema
      description: '- the file name of the zip file is not determined by this endpoint'
      responses:
        '200':
          description: 'A zip file with all schema templates'
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error

  '/clinical/template/{schema}':
    parameters:
      - name: schema
        description: name of the schema to download the template file for
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Download the template file for a given schema
      description: |
        - the file name of tsv file is not determined by this endpoint
        - this endpoint will accept /{schema} or /{schema}.tsv
      responses:
        '200':
          description: 'A tsv template file for the given schemaName'
          content:
            text/tab-separated-values:
              schema:
                example: 'program_id\tsubmitter_donor_id\tgender\tsubmitter_specimen_id\tspecimen_type\ttumour_normal_designation\tsubmitter_sample_id\tsample_type'
                type: string
        '404':
          description: The errror message indicating the schema could not be found
          content:
            application/json:
              schema:
                example: '{"message": "no schema named ''invalidName'' found"}'
                type: string
        '500':
          description: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  