openapi: 3.0.0
info:
  title: Platform-API
  version: 1.0.0
tags:
  - name: Kafka REST Proxy
    description: proxy for Kafka REST
  - name: Clinical Proxies
    description: Proxies requests for file download to Clinical service
  - name: Clinical API
    description: Custom requests for Clinical Data Download
  - name: File Centric TSVs
    description: download file-centric TSV files

paths:
  '/kafka/{topic}':
    parameters:
      - name: topic
        description: the name of the target topic in kafka
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
        - 'Kafka REST Proxy'
      security:
        - bearerAuth: []
      summary: proxies json messages to kafka rest proxy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                records:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: 'the successful response from kafka rest proxy'
          content:
            application/json:
              schema:
                type: object
        '401':
          description: invalid/missing jwt token
          content:
            application/json:
              schema:
                example: '{"message": "invalid jwt"}'
                type: string
        '500':
          description: Internal server error
          
  '/clinical/api/donors/data-for-files':
    post:
      tags:
        - Clinical API
      security:
        - bearerAuth: []
      summary: Download clinical data for a list of files.
      description: Download clinical data for a list of files.
      requestBody:
        description: JSON object containing search filters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                objectIds:
                  description: Array of files' object IDs. Must have at least one item.
                  type: array
                  items:
                    type: string
                  example: ['33eb128f-fcc5-5a1a-bb86-d6b3f96ed7b0']
      responses:
        '200':
          description: 'A zip file with all program submitted data'
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          description: The error message indicates something wrong with the request
        '500':
          description: Internal server error
  '/clinical/proxy/program/{programId}/all-clinical-data':
    parameters:
      - name: programId
        description: the short name of the program
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Clinical Proxies
      security:
        - bearerAuth: []
      summary: Download a zip file with tsv files for all clinical data in program
      description: '- the file name of the zip file is not determined by this endpoint'
      responses:
        '200':
          description: 'A zip file with all program submitted data'
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error
  '/clinical/proxy/program/{programId}/clinical-data':
    parameters:
      - name: programId
        description: the short name of the program
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
        - Clinical Proxies
      security:
        - bearerAuth: []
      summary: Query program data from clinical service
      description: 'Query program data by ID from clinical service'
      requestBody:
        description: JSON object containing search filters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completionState:
                  $ref: '#/components/schemas/CompletionState'
                  default: 'all'
                entityTypes:
                  type: array
                  items:
                    $ref: '#/components/schemas/EntityName'
                  default: []
                donorIds:
                  type: array
                  items:
                    type: number
                  default: []
                submitterDonorIds:
                  type: array
                  items:
                    type: string
                  default: []
      responses:
        '200':
          description: 'Returns clinicalEntities[], completionStats[] & clinicalErrors[]'
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal server error
  '/clinical/proxy/program/{programId}/clinical-errors':
    parameters:
      - name: programId
        description: the short name of the program
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
        - Clinical Proxies
      security:
        - bearerAuth: []
      summary: Query program data errors from clinical service
      description: 'Query program data errors by ID from clinical service'
      requestBody:
        description: JSON object containing search filters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                donorIds:
                  type: array
                  items:
                    type: number
                  default: []
      responses:
        '200':
          description: 'Returns clinicalEntities[], completionStats[] & clinicalErrors[]'
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal server error
  '/clinical/proxy/program/{programId}/clinical-search-results':
    parameters:
      - name: programId
        description: the short name of the program
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
        - Clinical Proxies
      security:
        - bearerAuth: []
      summary: Query donor IDs and submitter IDs matching a query on clinical service
      description: 'Query Donor IDs + Submitter IDs matching a filter from clinical service'
      requestBody:
        description: JSON object containing search filters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completionState:
                  $ref: '#/components/schemas/CompletionState'
                  default: 'all'
                entityTypes:
                  type: array
                  items:
                    $ref: '#/components/schemas/EntityName'
                  default: []
                donorIds:
                  description: List of donor IDs or partial IDs to search for. Results will be returned for any partial matches with the input strings.
                  type: array
                  items:
                    type: string
                  default: []
                submitterDonorIds:
                  description: List of submitter donor IDs or partial IDs to search for. Results will be returned for any partial matches with the input strings.
                  type: array
                  items:
                    type: string
                  default: []
      responses:
        '200':
          description: 'Returns donorId[] & submitterDonorId[]'
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal server error
  '/clinical/proxy/program/{programId}/clinical-data-tsv':
    parameters:
      - name: programId
        description: the short name of the program
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
        - Clinical Proxies
      security:
        - bearerAuth: []
      summary: Download a zip file with tsv files for filtered clinical data in program
      description: 'Download a zip file with tsv files for filtered clinical data in program'
      requestBody:
        description: JSON object containing search filters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completionState:
                  $ref: '#/components/schemas/CompletionState'
                  default: 'all'
                entityTypes:
                  type: array
                  items:
                    $ref: '#/components/schemas/EntityName'
                  default: []
                donorIds:
                  type: array
                  items:
                    type: number
                  default: []
                submitterDonorIds:
                  type: array
                  items:
                    type: string
                  default: []
      responses:
        '200':
          description: 'A zip file with all program submitted data'
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error
  '/clinical/proxy/template/all':
    get:
      tags:
        - Clinical Proxies
      summary: Download a zip file with templates for all schema, with the option to exclude sample registration.
      description: '- the file name of the zip file is not determined by this endpoint'
      parameters:
        - name: excludeSampleRegistration
          in: query
          description: Boolean value for whether to exclude downloading sample registration file. Accepted values are "true" or "false", default to false.
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: 'A zip file with all schema templates'
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error
  '/clinical/proxy/template/{schema}':
    parameters:
      - name: schema
        description: name of the schema to download the template file for
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Clinical Proxies
      summary: Download the template file for a given schema
      description: |
        - the file name of tsv file is not determined by this endpoint
        - this endpoint will accept /{schema} or /{schema}.tsv
      responses:
        '200':
          description: 'A tsv template file for the given schemaName'
          content:
            text/tab-separated-values:
              schema:
                example: 'program_id\tsubmitter_donor_id\tgender\tsubmitter_specimen_id\tspecimen_type\ttumour_normal_designation\tsubmitter_sample_id\tsample_type'
                type: string
        '404':
          description: The errror message indicating the schema could not be found
          content:
            application/json:
              schema:
                example: '{"message": "no schema named ''invalidName'' found"}'
                type: string
        '500':
          description: Internal server error
  '/file-centric-tsv/score-manifest':
    parameters:
      - name: filter
        description: JSON filter following the SQON spec
        in: query
        required: false
        schema:
          type: string
      - name: fileName
        description: What to name the file. Will always come with .tsv extension
        in: query
        required: false
        schema:
          type: string
    get:
      tags:
        - File Centric TSVs
      security:
        - bearerAuth: []
      summary: Download the score manifest tsv file
      responses:
        '200':
          description: 'The manifest file for use with Score'
        '400':
          description: The error message indicates something wrong with the request
          content:
            application/json:
              schema:
                example: 'asdf is not a valid filter'
                type: string
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CompletionState:
      type: string
      enum: [all, invalid, complete, incomplete]

    EntityName:
      type: string
      enum:
        [
          donor,
          sampleRegistration,
          specimens,
          primaryDiagnoses,
          familyHistory,
          treatment,
          treatments,
          chemotherapy,
          immunotherapy,
          surgery,
          radiation,
          followUps,
          hormoneTherapy,
          exposure,
          comorbidity,
          biomarker,
        ]
