# For a quick mongo/elasticSearch local enviornment

version: '3'
services:
  elasticsearch:
    image: 'elasticsearch:7.5.0'
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=workflow.elasticsearch
      - 'ES_JAVA_OPTS=-Xms512m -Xmx2048m'

  kibana:
    image: 'kibana:7.5.0'
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  es_data:
    driver: local
